In [1]:
import torch

a = torch.ones(3)

print(a)
print(a[0])
print(float(a[0]))

a[0] = 2

print(a)

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([2., 1., 1.])


In [2]:
points = torch.zeros(6)
print(points)

points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

print(points)


tensor([0., 0., 0., 0., 0., 0.])
tensor([4., 1., 5., 3., 2., 1.])


In [3]:
points = torch.tensor([[4,1],[5,3],[2,1]])

print(points)
print(points.shape)
print(points[0,1])
print(points[0])

tensor([[4, 1],
        [5, 3],
        [2, 1]])
torch.Size([3, 2])
tensor(1)
tensor([4, 1])


In [4]:
l = list(range(6))
print(l[:])           # All elements in the list
print(l[1:4])         # From element 1 inclusive to elemnt 4 exclusive
print(l[1: ])         # From element 1 inclusive to the end to the list  
print(l[ :4])         # From the start of the list to element 4 exclusive
print(l[ :-1])        # From the start of the list to one before last element
print(l[ 1: 4 : 2])   # From element 1 to 4 exclusive in step of 2 

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [5]:
print(points)
print(points[1:])     # All rows after first
print(points[1:, :])  # All rows after first 
print(points[1:, 0])  # All rows after first; only first column 
print(points[None])   # Add a dimension of size 1 just like unsqueeze

tensor([[4, 1],
        [5, 3],
        [2, 1]])
tensor([[5, 3],
        [2, 1]])
tensor([[5, 3],
        [2, 1]])
tensor([5, 2])
tensor([[[4, 1],
         [5, 3],
         [2, 1]]])


In [28]:
img_t = torch.randn(3,5,5)                        #shape [chanel, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5,5)                  #shape [batch, chanel, rows, columns]
print(img_t)
print(weights)
print(batch_t)

tensor([[[-1.0052,  0.2439,  0.6927,  1.0015,  0.2687],
         [ 1.8434,  0.1360, -1.1197, -0.1583, -0.7591],
         [-1.2620, -0.1836,  2.2000, -0.2134,  0.4101],
         [-0.0959,  1.0604,  0.0644,  0.0646, -0.2886],
         [-0.0457, -1.4722, -2.3351, -0.4436, -0.2544]],

        [[-1.6041, -0.7830,  1.0378, -0.4654,  0.9429],
         [ 0.4101, -0.8059,  1.1984,  0.8404, -1.0461],
         [-0.5098,  0.4541, -0.8013,  1.5790,  1.2551],
         [-1.3930, -0.7973,  0.1408,  0.0168,  0.3379],
         [-0.4191, -0.5334, -0.0347, -1.9127,  1.4194]],

        [[-0.5805, -0.8958, -0.5209, -0.7420,  0.0743],
         [ 0.2575,  0.9388,  0.9768,  1.6302,  1.1595],
         [ 0.5513, -0.1940, -1.0356, -0.6961,  0.8471],
         [-0.3066, -0.6416,  2.3654, -0.4141, -1.2021],
         [ 0.4234, -1.1206, -0.6071,  0.2269,  0.0530]]])
tensor([0.2126, 0.7152, 0.0722])
tensor([[[[ 0.7438, -0.1002, -2.2192, -0.4474, -1.5613],
          [-0.6929, -0.2255,  0.9478, -0.4188, -0.9918],
       

In [29]:
img_gray_naive = img_t.mean(-3)                   # Chanel always in dimention -3
batch_gray_naive = batch_t.mean(-3)

print(img_gray_naive)
print(batch_gray_naive)

print(img_gray_naive.shape, batch_gray_naive.shape)

tensor([[-1.0633, -0.4783,  0.4032, -0.0686,  0.4287],
        [ 0.8370,  0.0896,  0.3518,  0.7707, -0.2152],
        [-0.4068,  0.0255,  0.1210,  0.2232,  0.8374],
        [-0.5985, -0.1262,  0.8569, -0.1109, -0.3843],
        [-0.0138, -1.0421, -0.9923, -0.7098,  0.4060]])
tensor([[[ 0.4980, -0.0725, -1.0854, -0.6867, -0.7843],
         [-0.8619, -0.3204,  1.1508, -0.5226,  0.2575],
         [-0.3011, -0.2771, -0.1880, -0.2189, -0.4269],
         [ 0.5013, -0.0218, -0.4167, -0.0956,  0.1138],
         [-0.8086, -0.5582, -0.9048, -0.7499, -0.2305]],

        [[ 0.2666, -0.5974,  0.3913,  0.0717, -1.0341],
         [-0.8058,  0.1286,  0.6042, -0.3370,  0.3415],
         [-0.6787, -0.6784,  0.2208, -0.5808,  1.0161],
         [ 0.7482,  0.4855, -0.3597, -1.1134,  0.1700],
         [-1.1184,  0.2250,  0.3524, -0.0685, -0.8953]]])
torch.Size([5, 5]) torch.Size([2, 5, 5])


In [30]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
print(unsqueezed_weights)
print(unsqueezed_weights.shape)

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])
torch.Size([3, 1, 1])


In [34]:
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

print(img_weights)
print(batch_weights)
print(img_gray_weighted)
print(batch_gray_weighted)

print(batch_weights.shape, batch_t.shape, unsqueezed_weights.shape)


tensor([[[-0.2137,  0.0518,  0.1473,  0.2129,  0.0571],
         [ 0.3919,  0.0289, -0.2380, -0.0337, -0.1614],
         [-0.2683, -0.0390,  0.4677, -0.0454,  0.0872],
         [-0.0204,  0.2254,  0.0137,  0.0137, -0.0614],
         [-0.0097, -0.3130, -0.4964, -0.0943, -0.0541]],

        [[-1.1472, -0.5600,  0.7422, -0.3328,  0.6744],
         [ 0.2933, -0.5764,  0.8571,  0.6011, -0.7482],
         [-0.3646,  0.3248, -0.5731,  1.1293,  0.8976],
         [-0.9963, -0.5702,  0.1007,  0.0120,  0.2417],
         [-0.2997, -0.3815, -0.0248, -1.3679,  1.0152]],

        [[-0.0419, -0.0647, -0.0376, -0.0536,  0.0054],
         [ 0.0186,  0.0678,  0.0705,  0.1177,  0.0837],
         [ 0.0398, -0.0140, -0.0748, -0.0503,  0.0612],
         [-0.0221, -0.0463,  0.1708, -0.0299, -0.0868],
         [ 0.0306, -0.0809, -0.0438,  0.0164,  0.0038]]])
tensor([[[[ 1.5814e-01, -2.1302e-02, -4.7181e-01, -9.5107e-02, -3.3194e-01],
          [-1.4731e-01, -4.7945e-02,  2.0151e-01, -8.9028e-02, -2.1087e-01],


In [38]:
weighted_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['chanels'])
print(weighted_named)

tensor([0.2126, 0.7152, 0.0722], names=('chanels',))


In [40]:
img_named = img_t.refine_names(..., 'chanels', 'rows','columns')
batch_named = batch_t.refine_names(..., 'chanels', 'rows','columns')

print(img_named)
print(batch_named)

print(img_named.shape, img_named.names)
print(batch_named.shape, batch_named.names)

tensor([[[-1.0052,  0.2439,  0.6927,  1.0015,  0.2687],
         [ 1.8434,  0.1360, -1.1197, -0.1583, -0.7591],
         [-1.2620, -0.1836,  2.2000, -0.2134,  0.4101],
         [-0.0959,  1.0604,  0.0644,  0.0646, -0.2886],
         [-0.0457, -1.4722, -2.3351, -0.4436, -0.2544]],

        [[-1.6041, -0.7830,  1.0378, -0.4654,  0.9429],
         [ 0.4101, -0.8059,  1.1984,  0.8404, -1.0461],
         [-0.5098,  0.4541, -0.8013,  1.5790,  1.2551],
         [-1.3930, -0.7973,  0.1408,  0.0168,  0.3379],
         [-0.4191, -0.5334, -0.0347, -1.9127,  1.4194]],

        [[-0.5805, -0.8958, -0.5209, -0.7420,  0.0743],
         [ 0.2575,  0.9388,  0.9768,  1.6302,  1.1595],
         [ 0.5513, -0.1940, -1.0356, -0.6961,  0.8471],
         [-0.3066, -0.6416,  2.3654, -0.4141, -1.2021],
         [ 0.4234, -1.1206, -0.6071,  0.2269,  0.0530]]],
       names=('chanels', 'rows', 'columns'))
tensor([[[[ 0.7438, -0.1002, -2.2192, -0.4474, -1.5613],
          [-0.6929, -0.2255,  0.9478, -0.4188, -0.99